import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "جمعية تعايش معي للرفق بـالـحـيـوان",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className="p-0 m-0">
        {children}
      </body>
    </html>
  );
}
